### ISSUE TITLE
[Request]: Star Systems to Travel to

### ISSUE THREAD

**Issue by BraveCaperCat2** [zer0Kerbal/SimpleHyperdrive#79]
### Description of the new feature / enhancement

Can you add a star system (or star systems) to travel to with this/these warp drives?

### Proposed technical implementation details

add new star system(s) (DON'T MAKE THEM ORBIT KERBOL!) with unique planets (or procedurally generated ones) orbiting them - don't forget to add moons (or muns as I like to call them) orbiting (some) of those planets.

**Comment by BraveCaperCat2** [comment]
> 👍 Thank you @BraveCaperCat2 :octocat:
> 
> ❓❔
> 
> Have you reviewed the open issues logs and recent changelogs?
> 
> In order to help us help you, please provide:
> 
> * <KSP_ROOT>/KSP.LOG
> * and one of the following:
>   
>   * if Module Manger is installed
>     
>     * <KSP_ROOT>/GameData/ModuleManager.ConfigCache
>   * if Module Manger /L is installed
>     
>     * <KSP_ROOT>/PluginData/ModuleManager/ConfigCache.cfg
> * Screenshots of issue (if appropriate) (images tell a much stronger tale)
> 
> You can archive these files (rar or zip, sadly no 7zip) and drag-n-drop them into an issue comment
> 
> 📳👀Please either watch this repositiory for updates.
> 
> 💬Kindly read our simple guides to:
> 
> * [contributing](https://github.com/zer0Kerbal/.github/blob/master/.github/CONTRIBUTING.md)
> * our expected [code of conduct](https://github.com/zer0Kerbal/.github/blob/master/.github/CODE_OF_CONDUCT.md) (hint: we are all adults here)
> * our [style guide.md](https://github.com/zer0Kerbal/.github/blob/master/.github/STYLEGUIDE.md)
>   These are boilerplate.'

but this is a feature request, not a bug.

**Comment by zer0Kerbal** [comment]
> Can you add a star system (or star systems) to travel to with this/these warp drives?

I could, but don't have to since [Kopernicus](https://forum.kerbalspaceprogram.com/index.php?/topic/200143-*/) allows others to do such. Kopernicus doesn't add planets, but adds the ability to add planets, rings, and so much more. It is a fantastic addon.

Example Planet Packs for KSP - [Outer Planets Mod (OPM)](https://forum.kerbalspaceprogram.com/index.php?/topic/184789-*/) It is a fantastic addon originally by  _@CaptRobau_, then by _@Galileo_, and now by _@Poodmund_

So many planets, systems, and yes, even galaxies for KSP. Some are in the Kerbol sphere-of-influence (SOI), some are in others.

I've considered adopting planet packs; however I still have a plethora of addons already adopted that are all screaming at me "When are you going to release us? update us? Give us some TLC!".

I must politely decline due to time constraints.

> but this is a feature request, not a bug.

it's general boilerplate. :)
